[theme]

# Primary accent for interactive elements
primaryColor = '#f58f7c'

# Background color for the main content area
backgroundColor = '#2c2b30'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#4f4f51'

# Color used for almost all text
textColor = '#d6d6d6'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"